name: Build & Deploy PDF Generator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 337909777634.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t pdf-api .

      - name: Tag Docker image
        run: docker tag pdf-api 337909777634.dkr.ecr.eu-west-1.amazonaws.com/pdf-api:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 337909777634.dkr.ecr.eu-west-1.amazonaws.com/pdf-api:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster pdf-cluster --service pdf-service --force-new-deployment